---
title: "Investigación abierta"
author: "Gabriela Ruz"
date: "24-11-2021"
output: html_document
---
# Los años de escolaridad según la pobreza multidimensional, el nivel de escolaridad de la madre y el sexo: un análisis de regresión múltiple

Autores: Gabriela Ruz, Fabian Alarcon, Martin Henriquez, Nicolás Gajardo y Gabriela Zenteno.
---

## Descripción

En la sociedad chilena, la educación constituye un valor muy apreciado por la población, que ve en ella la única forma de progresar en la vida. Por ello, la mayoría de las
personas se encuentran dispuestas a realizar grandes esfuerzos para obtener un buen nivel
educacional (Oliva, 2018). Sin embargo, existen factores vinculados a desigualdades
socioeconómicas y demográficas de origen que obstruyen la posibilidad de dedicar más
tiempo de vida a los estudios, de obtener un buen desempeño educativo, o de prevenir la
deserción o retraso. La presente investigación busca analizar en que medida las variables
nivel de escolaridad alcanzado por la madre, sexo y pobreza multidimensional, influyen en
los años de escolaridad de las personas, entendiendo que dichas variables proveen
información sobre las circunstancias socioeconómicas que caracterizarán la trayectoria
educacional. Se elaborará un modelo de regresión múltiple a partir de los datos proporcionados por la encuesta [CASEN 2017](http://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-casen-2017).

Este trabajo sigue el protocolo de investigación reproducible IPO, el cual sigue la lógica del protocolo [TIER](https://www.projecttier.org/), pero con algunas innovaciones, para más información revisar la página: https://juancarloscastillo.github.io/ipo/

Para mayor información, visite el siguiente [link](https://gabrielaruzal.github.io/IPO_a-osdeescolaridad/) o visite el preregistro que se encuentra en la siguiente [página](https://osf.io/4evrw)

## Instalación

Debe instalar el programa [Rstudio](https://www.rstudio.com/about/), el cual, puede descargar mediante el siguiente link: https://www.rstudio.com/products/rstudio/download/

Y debe descargar el archivo de R según su sistema operativo, el cual, es el codigo libre, es decir, de Open source disponible en la siguiente página: https://www.r-project.org/

Luego, descargue la base de datos de la CASEN 2017 en: http://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-casen-2017

## Uso

Se espera que se realize el analisis de la base de datos de la CASEN 2017 en el programa Rstudio. 

## Soporte

Si se requiere ayuda, no dudar contactar a Gabriela Ruz, en el siguiente correo: "gabriela.ruz@ug.uchile.cl"


## Contribución

El proyecto ha sido planteado bajo los preceptos de la ciencia abierta, es decir, se busca generar un proyecto transparente, reproducible y  accesible para el mundo cientifico. 

Si desea contribuir con este proyecto debe seguir los  de la licencia que GNU General Public License (GPL) 3.0, cuyos permisos, condiciones y limitaciones se encuentran en la siguiente página: https://choosealicense.com/licenses/gpl-3.0/

## Autores y contribuyentes

Se agradece el apoyo y contribución a este proyecto a Gabriela, Monserrat Greene, Carmen Molina, Fabián Alarcón, Gabriela Zenteno, Nicolás Gajardo, y Martín Henriquez. 

## Licencia

La licencia del projecto es la [GNU General Public License (GPL) 3.0](http://www.gnu.org/licenses/)

## Estado del proyecto 

El proyecto ha sido completado. 

