<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Gabriela Ruz, Fabian Alarcon, Martin Henriquez, Nicolás Gajardo y Gabriela Zenteno." />


<title>Los años de escolaridad según la pobreza multidimensional, el nivel de escolaridad de la madre y el sexo: un análisis de regresión múltiple</title>

<script src="site_libs/header-attrs-2.9/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>




<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
#TOC {
  display: none !important;
}
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Investigación abierta</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="reporte.html">reporte</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="(gabriela.ruz@ug.uchile.cl)">
    <span class="fa fa-envelope fa-lg"></span>

  </a>
</li>
<li>
  <a href="https://github.com/gabrielaruzal/IPO_a-osdeescolaridad/">
    <span class="fa fa-github fa-lg"></span>

  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Los años de escolaridad según la pobreza multidimensional, el nivel de escolaridad de la madre y el sexo: un análisis de regresión múltiple</h1>
<h4 class="author">Gabriela Ruz, Fabian Alarcon, Martin Henriquez, Nicolás Gajardo y Gabriela Zenteno.</h4>
<h4 class="date">8/10/2021</h4>

</div>


<div style="text-align: justify">
<div id="resumen" class="section level3">
<h3>Resumen</h3>
<p>En la sociedad chilena, la educación constituye un valor muy apreciado por la población, que ve en ella la única forma de progresar en la vida. Por ello, la mayoría de las personas se encuentran dispuestas a realizar grandes esfuerzos para obtener un buen nivel educacional <span class="citation">(<a href="#ref-oliva_88_2018" role="doc-biblioref">Oliva 2018</a>)</span>. Sin embargo, existen factores vinculados a desigualdades socioeconómicas y demográficas de origen que obstruyen la posibilidad de dedicar más tiempo de vida a los estudios, de obtener un buen desempeño educativo, o de prevenir la deserción o retraso. La presente investigación busca analizar en que medida las variables nivel de escolaridad alcanzado por la madre, sexo y pobreza multidimensional, influyen en los años de escolaridad de las personas, entendiendo que dichas variables proveen información sobre las circunstancias socioeconómicas que caracterizarán la trayectoria educacional. Se elabora un modelo de regresión múltiple a partir de los datos proporcionados por la encuesta <a href="http://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-casen-2017">CASEN 2017</a>, con una base filtrada de N=51.472 (personas).Los resultados mostraron una relación significativa entre la variable dependiente con todas las demás variables independientes (p&lt;.001). Estar en una situación de pobreza multidimensional disminuye los años de escolaridad del entrevistado/a, y a medida que aumenta el nivel de escolaridad de la madre, aumentan los años de escolaridad. Respecto al sexo, los años de escolaridad disminuyen en un -0.285 en el caso de las mujeres, y en cuanto a edad, disminuirían en un -0,079 a medida que aumenta. Se concluye la relevancia predictiva del modelo, con un R cuadrado ajustado de 0.425.</p>
<p>Palabras clave: “Escolaridad”; Pobreza multidimensional”; “Sexo”; “Regresión múltiple”.</p>
<pre><code>## [1] &quot;/home/juank/github/esco2&quot;</code></pre>
</div>
<div id="introducción" class="section level2">
<h2>1.Introducción</h2>
<p>La educación y la adquisición de conocimiento han sido temas prioritarios en las discusiones sobre desarrollo social, dado que constituye una puerta de entrada para la mejora de la expectativa de vida de las personas <span class="citation">(<a href="#ref-rivero_reforma_2000" role="doc-biblioref">Rivero 2000</a>)</span>, para alentar el crecimiento económico de los países y mejorar sus condiciones de competencia en un mundo globalizado <span class="citation">(<a href="#ref-garbanzo_vargas_factores_2014" role="doc-biblioref">Garbanzo Vargas 2014</a>)</span>.</p>
<p>En Chile, según datos del CENSO 2017 <span class="citation">(<a href="#ref-sierra_determinantes_2019" role="doc-biblioref">Sierra et al. 2019</a>)</span>, la población de 15 años o más tiene en promedio 11,05 años de escolaridad. No obstante, el nivel educativo dista de ser equitativo en todos los grupos de la sociedad. Las cifras de CASEN <span class="citation">socioeconómica. (<a href="#ref-encuesta_de_caracterizacion_socioeconomica_observatorio_2017" role="doc-biblioref">2017</a>)</span> cuentan que de casi 5 millones de adultos sin escolaridad completa, el 50,4% son mujeres, versus 44,1% de hombres. Entre las razones que pudiesen justificar esta cifra encontramos la necesidad de cuidar familiares. De hecho, la mayor parte de las mujeres fuera de la fuerza de trabajo, esto es 1.300.669 personas (34,7%), señaló que no trabaja debido a razones familiares permanentes, pues deben cuidar a hijos, hijas u otros familiares. En cambio, solo 2,3% de los hombres (45.527 personas) entregó esta razón para no trabajar y/o estudiar <span class="citation">(<a href="#ref-instituto_nacional_de_estadistica_sintesis_2017" role="doc-biblioref">Estadística 2017</a>)</span>.</p>
<p>El análisis de Deserción Escolar en Chile realizado por la Universidad del Desarrollo (2017) señala que tanto los hombres desertores como las mujeres desertoras responden según un set de valores en el que hay una mayor tendencia hacia una clara delimitación de los roles de género. Esta delimitación se produce hacia una concepción tradicional de género en que la mujer se dedica a la crianza y el hombre es proveedor. También, se ha observado que las madres con menor escolaridad aumentan la probabilidad de deserción en los/as hijos/as, así como sus expectativas académicas (Román, 2013). Asimismo, niveles de pobreza y vulnerabilidad social mayores juegan en contra de la posibilidad de alcanzar mayores niveles de escolaridad <span class="citation">(<a href="#ref-catro_d_pobreza_2013" role="doc-biblioref">Catro D. and Cano G. 2013</a>)</span>. Si bien los objetivos que posee el sistema educacional chileno se relacionan con garantizar calidad, herramientas y asegurar ciertos años de escolaridad para la población <span class="citation">(<a href="#ref-chile_indicadores_2006" role="doc-biblioref">Chile, Ministerio de Educación, and Departamento de Estudios y Desarrollo 2006</a>)</span>, estos propósitos pueden verse afectados por ciertas desigualdades de origen, como el sexo, los niveles de pobreza y la escolaridad familiar.</p>
<p>En base a esto, el presente trabajo se propone indagar en la relación existente entre la variable dependiente <strong>años de escolaridad</strong> de la población chilena, y factores de índole socioeconómico y sociodemográfico, a saber; <strong>nivel de escolaridad alcanzado por la madre</strong>, <strong>sexo</strong> y <strong>pobreza multidimensional</strong>. Proponemos que estas variables influyen directamente en los años de escolaridad que alcanzan las personas, así como también sus posibilidades para encontrar empleos y tener buenos salarios.</p>
<div id="pregunta-de-investigación" class="section level3">
<h3>1.1 Pregunta de investigación</h3>
<p>¿De qué manera inciden las variables <strong>pobreza multidimensional</strong>, <strong>nivel de escolaridad de la madre</strong> y <strong>sexo</strong> en <strong>los años de escolaridad</strong> de la población chilena, controlado por la variable edad?</p>
<p>### 1.2 Objetivos</p>
<p>#### 1.2.1 Objetivo general</p>
<ul>
<li>Analizar la incidencia de las variables pobreza multidimensional, nivel de escolaridad de la madre y sexo en los años de escolaridad de la población chilena, controlado por la variable edad</li>
</ul>
<div id="objetivos-específicos" class="section level4">
<h4>1.2.2 Objetivos específicos</h4>
<ul>
<li>Realizar una descripción univariada de las variables pobreza multidimensional, nivel de escolaridad de la madre, sexo, y años de escolaridad</li>
<li>Analizar la relación de las variables pobreza multidimensional, nivel de escolaridad de la madre, y sexo en la variabilidad de los años de escolaridad.</li>
</ul>
</div>
</div>
<div id="hipotesis" class="section level3">
<h3>1.3 Hipotesis</h3>
<p>Se plantea que los años de escolaridad tienden a ser mayores en personas que 1) no presenten situación de pobreza multidimensional, 2) presenten mayor nivel de escolaridad de la madre o figura materna y 3) se declaren de sexo masculino.</p>
<p><strong>Criterios de contraste de hipotesis</strong></p>
<p>Se plantea que los años de escolaridad tienden a ser mayores en personas que: 1) presenten situación de pobreza multidimensional, 2) no presenten mayor nivel de escolaridad de la madre o figura materna y 3) se declaren de femenino.</p>
</div>
</div>
<div id="antecedentes" class="section level2">
<h2>2. Antecedentes</h2>
<p>En relación a los antecedentes de la relación a indagar, el poseer más años de escolaridad puede implicar un mejor desempeño laboral a futuro, por lo que es importante observar qué factores inciden en la posibilidad de las personas de alcanzar un mejor nivel educativo. Existe vasta literatura acerca de aspectos sociodemográficos, psicosociales, socioeconómicos, e institucionales que inciden en la trayectoria educacional, incluso pudiendo ser un gran factor del éxito académico y en casos de rezago o deserción <span class="citation">(<a href="#ref-montero_rojas_factores_2014" role="doc-biblioref">Montero Rojas, Villalobos Palma, and Valverde Bermúdez 2014</a>)</span>.</p>
<p>Se plantea que los años de escolaridad tienden a ser mayores en personas cuyas condiciones tales como salud y empleabilidad son mejores <span class="citation">(<a href="#ref-shrestha_multigenerational_2020" role="doc-biblioref">Shrestha and Shrestha 2020</a>)</span>, y por el contrario, existe evidencia de que tienden a disminuir en personas con mayores niveles de vulnerabilidad social, que se ven en necesidad de percibir ingresos lo antes posible, muchas veces abandonando de manera prematura la enseñanza, o bien teniendo dificultades de asistencia, concentración, y/o desempeño educativo <span class="citation">(<a href="#ref-sierra_determinantes_2019" role="doc-biblioref">Sierra et al. 2019</a>)</span>.</p>
<p>En relación a esto, la pobreza multidimensional como medida asociada a la vulnerabilidad social, consiste en 5 dimensiones que pueden ser claves con respecto al período de escolaridad de una persona (Educación, Salud, Trabajo y Seguridad Social, Vivienda y Entorno, Redes y Cohesión Social). El bajo desempeño de estas dimensiones puede tener una afección negativa en los años de escolaridad <span class="citation">(<a href="#ref-herrera_macguire_rezago_2020" role="doc-biblioref">Herrera MacGuire 2020</a>)</span>. En cuanto al nivel de escolaridad de la madre, estudios arrojan diferencias en la escolaridad de los hijos dependiendo del sexo del/a jefe/a en hogares monoparentales, en desmedro de hogares de jefatura femenina <span class="citation">(<a href="#ref-sierra_determinantes_2019" role="doc-biblioref">Sierra et al. 2019</a>)</span>.</p>
<p>Según la encuesta CASEN 2017, el 73% de los hogares con jefatura femenina son monoparentales. Esto implicaría menores probabilidades, tanto de hijos/as como las mismas madres, de poseer más años de escolaridad que en hogares encabezados por hombres, en su mayoría biparentales (79,2%), ya que, las mujeres abocadas a la crianza suelen tener un limitado acceso al campo laboral, y en general deben cargar solas con la educación de sus hijos/as <span class="citation">(<a href="#ref-escamilla_r_familias_2013" role="doc-biblioref">Escamilla R, Parra, and Vásquez 2013</a>)</span>.</p>
<p>En cuanto a la variable sexo, el promedio de años de escolaridad de la población de 25 años o más también aumentó, pasando de 8,23 en 1992 a 11,05 en 2017. No obstante, en las mujeres, el promedio creció de 8,08 a 10,95 en el mismo lapso y el de hombres, de 8,39 a 11,16 (INE, 2018). Así, se vislumbra que el género influye en los logros educativos, y que esta situación se sigue sosteniendo a lo largo del tiempo <span class="citation">(<a href="#ref-zeng_gender_2014" role="doc-biblioref">Zeng et al. 2014</a>)</span>. Finalmente, se introducirá un control por edad para parcializar las diferencias que podrían existir en función de esta variable.</p>
</div>
<div id="metodología" class="section level2">
<h2>3.Metodología</h2>
<div id="descripción-de-la-base-de-datos" class="section level3">
<h3>3.1 Descripción de la base de datos</h3>
<p>Los datos utilizados para esta investigación fueron extraídos de un estudio a cargo del Ministerio de Desarrollo Social, a partir de la Encuesta de Caracterización Socioeconómica <a href="http://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-casen-2017">CASEN 2017</a> que integra siete módulos; registro de residentes, educación, trabajo, ingresos, salud, redes y participación, vivienda y entorno e identidades <span class="citation">(<a href="#ref-encuesta_de_caracterizacion_socioeconomica_observatorio_2017" role="doc-biblioref">socioeconómica. 2017</a>)</span>. El objetivo de la encuesta es conocer periódicamente la situación de los hogares y de la población en situación de pobreza y grupos definidos como prioritarios. La cobertura geográfica del estudio es a nivel nacional y corresponde a un total de 68.466 viviendas efectivas, 70.948 hogares, 216.439 personas perteneciente a hogares y 83.232 núcleos familiares.</p>
<p>La base cuenta con 804 variables en total. Para efectos de la presente investigación, la base filtrada, es decir, sin los NA, que se utilizará cuenta con 5 variables, 1 dependiente, 2 predictores y 2 de control contando con 51.472 casos válidos (individuos).</p>
</div>
<div id="variables" class="section level3">
<h3>3.2 Variables</h3>
<p>Se consideró la variable dependiente “Años de escolaridad” (escolaridad), variable continua que consiste en el número de años de estudio de una persona. Luego, las variables predictoras son “Nivel de educación más alto alcanzado por la madre” (educacion_madre), considerando 5 niveles que se encuentran indicados en la Tabla 1, recodificados a partir de la categorización CINE de la UNESCO (2011), donde:</p>
<p>1 = Primaria incompleta o menos 2 = Primaria y secundaria baja 3 = Secundaria alta 4 = Terciaria de ciclo corto 5 = Terciaria y postgrado</p>
<p>También se encuentra el predictor “Situación de pobreza multidimensional” (pobreza_multidimensional), que es una medición basada en 5 dimensiones (Educación, Salud, Trabajo y Seguridad Social, Vivienda y Entorno, Redes y Cohesión Social), y que se expresa como variable dummy (0 = No es pobre; 1 = Si es pobre). En tercer lugar, se incluye la variable “Sexo” dicotómica con categorías Hombre (0) y Mujer (1), y control por “Edad” como variable continua.</p>
</div>
<div id="método" class="section level3">
<h3>3.3 Método</h3>
<p>Con el objetivo de dar cuenta de la capacidad predictiva de las variables independientes frente a la dependiente, en primer momento se efectuará una descripción de cada una, con sus respectivos estadísticos. Luego, se procederá con un análisis bivariado que considere las correlaciones entre estas, incluyendo gráficos de caja para las variables dicotómicas. Finalmente se elaborará un modelo de regresión múltiple, que considerará de manera conjunta a las variables independientes para predecir los años de escolaridad. Se representa mediante la siguiente ecuación:</p>
<p><strong>Modelo Regresión Múltiple</strong></p>
<p>Años de escolaridad = 𝛽0 + 𝛽1 ∙ pobreza multidimensional + 𝛽2 ∙nivel de escolaridad de la madre + 𝛽3 ∙ sexo + 𝛽4 ∙ 𝑒𝑑𝑎𝑑 + 𝜀</p>
<p>Donde:</p>
<ul>
<li>Años de escolaridad es la variable a predecir</li>
<li>𝛽0 es el intercepto</li>
<li>𝛽𝑖 es el coeficiente de regresión, que indica cuánto varían los años de escolaridad por cada punto que aumentan las variables independientes.</li>
<li>𝜀 el error del modelo de regresión.</li>
</ul>
</div>
</div>
<div id="análisis" class="section level2">
<h2>4.Análisis</h2>
<div id="análisis-descriptivo-univariado" class="section level3">
<h3>4.1 Análisis Descriptivo Univariado</h3>
<p><strong>Tabla 1. Descripción de las variables</strong></p>
<table style="border-collapse:collapse; border:none;">
<caption>
Data frame: baseproc
</caption>
<tr>
<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">
ID
</th>
<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">
Name
</th>
<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">
Label
</th>
<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">
Values
</th>
<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">
Value Labels
</th>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
1
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
escolaridad
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
A?os de escolaridad
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;" colspan="2">
<em>range: 0-22</em>
</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
2
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
sexo
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
Sexo de entrevistado/a
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
0<br>1
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
Hombre<br>Mujer
</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
3
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
edad
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
Edad
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;" colspan="2">
<em>range: 18-105</em>
</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
4
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
pobreza_multidimensional
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
Situación de pobreza multidimensional con entorno<br>y redes (5 dimensiones)
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
0<br>1
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">
No es pobre<br>Si es pobre
</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
5
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
educacion_madre
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
Nivel de educaci?n m?s alto alcanzado por su madre<br>(o fig.materna)
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
1<br>2<br>3<br>4<br>5
</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">
1=Primaria incompleta menos<br>2=Primaria y secundaria baja<br>3=Secundaria alta<br>4=Terciaria ciclo corto<br>5=Terciaria y Postgrado
</td>
</tr>
</table>
<p>Se observa en la Tabla 1 que la media de años de escolaridad es de 10.8, con una desviación estándar de 4.6 años. En cuanto a pobreza multidimensional, un 16.8% de la muestra cae en esta categoría. Y en referencia al nivel educacional de la madre, se tiene que para un 46,7% su último nivel de enseñanza fue primaria y secundaria baja, siguiéndole con un 25.9% de secundaria alta, un 20,1% con primaria incompleta o menos, un 5,7% con terciaria y postgrado, y un 1,6% con terciaria de ciclo corto. Por el lado de sexo, la mayor parte de quienes responden son hombres, representando un 56.4%. En cuanto a la edad, se observa que la media etaria de los/as entrevistados es de 53 años, con una desviación estándar de 16.2 años.</p>
</div>
<div id="análisis-descriptivo-bivariado" class="section level3">
<h3>4.2 Análisis Descriptivo Bivariado</h3>
<p><strong>Gráfico 1. Años de escolaridad según sexo</strong></p>
<p><img src="output/graphs/graf_1.png" /></p>
<p>En el Gráfico 1 se observa que la mediana de años de escolaridad entre mujeres y hombres es similar. No obstante, el promedio es menor en mujeres, lo que sugiere un mayor peso de los casos inferiores extremos, haciendo que la media sea menor. A su vez, en el caso de los hombres existe una mayor dispersión de los casos, con un rango intercuartílico más amplio que el de las mujeres. Se evidencia que, en el caso de los hombres, un 75% de los casos posee 15 o menos años de escolaridad, mientras que en las mujeres es 13 años (rangos aproximados). Así, es posible dar cuenta de una mayor concentración de casos con menores años de escolaridad en mujeres, pese a que el caso de la mitad sea similar en ambos sexos. A su vez, al observar que el límite superior del rango intercuartílico y la mediana son menores en mujeres, es posible inferir que existe una diferencia de años de escolaridad a favor de los hombres.</p>
<p><strong>Gráfico 2. Años de escolaridad según pobreza multidimensional</strong></p>
<p><img src="output/graphs/graf_2.png" /></p>
<p>Por su parte, el Gráfico 2 plasma la diferencia, tanto en el promedio como en la mediana, de los años de escolaridad en referencia a la pobreza multidimensional, mostrando una tendencia más desfavorable para la categoría “Si es pobre”. En esta última, el 50% posee 8 años o menos de escolaridad, a diferencia de los no pobres, en donde el 50% alcanzan 12 o menos años (rangos aproximados). Asimismo, existe menor dispersión en la categoría de los “No pobres”, en comparación a la categoría “Si es pobre”. Esto va en coherencia con la hipótesis que señala que los “No pobres” tienen mayores probabilidades de alcanzar más años de escolaridad.</p>
<p><strong>Gráfico 3. Años de escolaridad y nivel de educación de madre</strong></p>
<p><img src="reporte_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Por su parte, el Gráfico 3 demuestra una tendencia al aumento de los años de escolaridad en función a un mayor nivel educativo de la madre. Se observa una mayor dispersión de años en los casos de nivel de educación más bajo, pero aún así el límite superior de su rango intercuartílico, su media y su mediana es menor en comparación a cualquiera de los demás niveles de educación. Esta tendencia también es concordante con la hipótesis que señala que a mayor nivel de escolaridad de la madre, mayores tienden a ser los años de escolaridad.</p>
<strong>Tabla 3. Matriz de correlaciones</strong>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Tabla Correlación
</caption>
<tr>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">

</th>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">
A?os de escolaridad
</th>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">
Sexo de entrevistado/a
</th>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">
Edad
</th>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">
Situación de pobreza multidimensional<br>con entorno y redes (5 dimensiones)
</th>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">
Nivel de educaci?n m?s alto alcanzado<br>por su madre (o fig.materna)
</th>
</tr>
<tr>
<td style="font-style:italic;">
A?os de escolaridad
</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
</tr>
<tr>
<td style="font-style:italic;">
Sexo de entrevistado/a
</td>
<td style="padding:0.2cm; text-align:center;">
-0.042<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
</tr>
<tr>
<td style="font-style:italic;">
Edad
</td>
<td style="padding:0.2cm; text-align:center;">
-0.444<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">
0.023<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
</tr>
<tr>
<td style="font-style:italic;">
Situación de pobreza multidimensional<br>con entorno y redes (5 dimensiones)
</td>
<td style="padding:0.2cm; text-align:center;">
-0.308<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center; color:#999999;">
-0.007<span style="vertical-align:super;font-size:0.8em;"></span>
</td>
<td style="padding:0.2cm; text-align:center;">
0.066<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">

</td>
<td style="padding:0.2cm; text-align:center;">

</td>
</tr>
<tr>
<td style="font-style:italic;">
Nivel de educaci?n m?s alto alcanzado<br>por su madre (o fig.materna)
</td>
<td style="padding:0.2cm; text-align:center;">
0.532<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">
-0.018<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">
-0.342<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">
-0.176<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">

</td>
</tr>
<tr>
<td colspan="6" style="border-bottom:double black; border-top:1px solid black; font-style:italic; font-size:0.9em; text-align:right;">
Computed correlation used pearson-method with listwise-deletion.
</td>
</tr>
</table>
<p>La Tabla de correlaciones arroja una relación de magnitud media para pobreza multidimensional y nivel educacional de la madre con respecto a la variable años de escolaridad (-0.308 y 0.532 respectivamente), siendo la primera relación negativa y la segunda positiva <span class="citation">(<a href="#ref-cohen_statistical_1988" role="doc-biblioref">Cohen 1988</a>)</span>. Se halla también una relación de tamaño pequeño para sexo y edad en relación a años de escolaridad <span class="citation">(<a href="#ref-cohen_statistical_1988" role="doc-biblioref">Cohen 1988</a>)</span>. Luego, las variables independientes tienen entre sí un efecto pequeño, a excepción de la edad con el nivel de educación de la madre, donde alcanza un efecto negativo de tamaño medio (-0.342), lo que implica que existe un nivel de variación compartida. Finalmente, cabe mencionar que cada una de estas relaciones es estadísticamente significativa, con un p&lt;.001, a excepción de la correlación entre sexo y situación de pobreza multidimensional, en donde existe una correlación no significativa de -0.007.</p>
</div>
<div id="modelo-de-regresión" class="section level3">
<h3>4.3 Modelo de regresión</h3>
<p><strong>Tabla 3. Modelo de regresión</strong></p>
<div class="figure">
<img src="output/tables/reg4.png" alt="" />
<p class="caption">Tabla 3</p>
</div>
<pre><code>## # A tibble: 2 x 2
##   pobreza_multidimensional mean_escolaridad
##                  &lt;dbl+lbl&gt;            &lt;dbl&gt;
## 1          0 [No es pobre]            11.4 
## 2          1 [Si es pobre]             7.62</code></pre>
<pre><code>## # A tibble: 2 x 2
##         sexo mean_escolaridad
##    &lt;dbl+lbl&gt;            &lt;dbl&gt;
## 1 0 [Hombre]             10.9
## 2 1 [Mujer]              10.5</code></pre>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">

</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Modelo 1
</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Modelo 2
</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Modelo 3
</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Modelo 4
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictores
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
??
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
std. Error
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
??
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
std. Error
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
??
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7">
std. Error
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col8">
??
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col9">
std. Error
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
11.405 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.021
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
7.426 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.039
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
7.573 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
0.041
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">
12.485 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">
0.074
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Situación de pobreza<br>multidimensional con<br>entorno y redes(5<br>dimensiones)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-3.787 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.052
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-2.563 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.044
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-2.567 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
0.044
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">
-2.573 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">
0.042
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Nivel de educaci?n m?s<br>alto alcanzado por su<br>madre(o fig materna):<br>2=Primaria y secundaria<br>baja
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
3.400 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.044
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
3.398 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
0.044
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">
2.744 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">
0.042
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Nivel de educaci?n m?s<br>alto alcanzado por su<br>madre(o fig materna):<br>3=Secundaria alta
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
6.173 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.049
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
6.167 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
0.049
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">
5.011 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">
0.049
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Nivel de educaci?n m?s<br>alto alcanzado por su<br>madre(o fig materna):<br>4=Terciaria ciclo corto
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
8.034 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.133
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
8.027 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
0.133
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">
6.275 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">
0.128
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Nivel de educaci?n m?s<br>alto alcanzado por su<br>madre(o fig materna):<br>5=Terciaria y Postgrado
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
8.005 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.078
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
7.991 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
0.078
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">
6.449 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">
0.076
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Sexo de entrevistado/a
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.331 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
0.033
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">
-0.285 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">
0.031
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Edad
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">
-0.079 <sup>***</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">
0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">
51472
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">
51472
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">
51472
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">
51472
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">
0.095 / 0.095
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">
0.356 / 0.356
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">
0.357 / 0.357
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">
0.425 / 0.425
</td>
</tr>
<tr>
<td colspan="9" style="font-style:italic; border-top:double black; text-align:right;">
<ul>
<li>p&lt;0.05   ** p&lt;0.01   *** p&lt;0.001
</td>
</tr></li>
</ul>
</table>
<p>En la Tabla 4, se observa que el Modelo 4 considera a todas las variables escogidas para el presente estudio. En relación a esto, es posible señalar que el intercepto de los años de escolaridad es de 12.485, lo que se interpreta como la línea base del análisis de cada variable independiente.</p>
<p>Respecto de la variable de pobreza multidimensional, el Modelo 4 señala que la escolaridad de una persona será más baja en 2.573 años al encontrarse en la categoría de pobreza multidimensional. Se presenta un valor p&lt;.001, siendo así estadísticamente significativa. Los intervalos de confianza son -2,573 y -2,615, por lo que se puede afirmar que los valores que toman son distintos de cero con un 99% de confianza.</p>
<p>En cuanto al nivel de educación más alto alcanzado por su madre, el Modelo 4 indica que el promedio de años de escolaridad para el grupo cuya figura materna mantiene nivel educacional primario y secundario bajo, es de 2.744 puntos más alto con respecto a las personas con educación primaria incompleta, siendo una relación estadísticamente significativa (p&lt; .001, SE = 0.042). El promedio de años de escolaridad para el grupo el grupo cuya figura materna mantiene nivel educacional secundario alto, es de 5.011 puntos más alto con respecto a las personas cuya madre posee educación primaria incompleta, siendo estadísticamente significativa (p&lt;.001, SE = 0.049). Luego, el promedio de años de escolaridad para el grupo cuya figura materna mantiene nivel educacional terciaria ciclo corto, es de 6.275 puntos más alto con respecto a las personas con educación primaria incompleta, siendo la diferencia estadísticamente significativa (p&lt; .001, SE = 0.128). Finalmente, para el grupo cuya figura materna mantiene nivel educacional primario y secundario bajo es de 6.449 años mayor con respecto a las personas con educación primaria incompleta, nuevamente con una significación estadística de p&lt; .001 (SE = 0.076).</p>
<p>En cuanto al sexo del/a entrevistado/a, el Modelo 4 señala que el sexo mujer posee en promedio 0.285 años de escolaridad menos que los hombres, con todo lo demás constante, siendo esta diferencia estadísticamente significativa (p&lt;.001, SE = .031). Por su parte, se observa que la variable edad logra capturar un nivel de variación de -0.079 años de escolaridad, también con una significancia estadística de p&lt;0.001 (SE = .001). Es decir, tanto para edad como sexo, es posible aseverar una diferencia significativa con un 99,9% de confianza.</p>
<p>Así, el Modelo 4 de regresión elaborado se expresa de la siguiente manera:</p>
<p>Años de escolaridad = 12.485 + (-2.573) ∙ Pobreza multidimensional + (2.744) ∙ Primaria y secundaria baja + (5.011) ∙ Secundaria alta + (6.275) ∙ Terciaria de ciclo corto + (6.449) ∙ Terciaria y postgrado + (-0.285) ∙ Sexo + (-0,079) ∙ Edad + 𝜀</p>
<p><strong>Gráfico 4. Coeficientes de regresión</strong> <img src="output/graphs/graf_4.png" /></p>
<p><img src="reporte_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>En el Gráfico 4 se observan los coeficientes beta de la regresión de modo de ver el impacto que tienen cada una de las variables sobre años de escolaridad. Los intervalos de confianza se obtienen sumando y restando el error estándar respectivo en cada variable. Así, se refleja la diferencia estadística de cada variable dentro del modelo. Es decir, se puede inferir con un 99,9% de confianza que estas variables no toman valores iguales a cero.</p>
</div>
<div id="ajuste-del-modelo" class="section level3">
<h3>4.4 Ajuste del modelo</h3>
<p>El modelo 4 presenta un R cuadrado ajustado de 0.425, es decir, del total de la varianza de los años de escolaridad, un 42.5% se puede explicar por las variables independientes incorporadas en el modelo. Se observa también en el Modelo 3, en donde no se incluye la variable de control “edad”, la varianza explicada disminuye a 35,7%, por lo que la inclusión de dicha variable aumenta la capacidad predictiva del modelo en un 6,8%. La variable sexo es aquella que menos logra explicar la varianza en años de escolaridad, con una diferencia de R cuadrado ajustado entre el modelo 2 y 3 de un 0.001.</p>
</div>
</div>
<div id="discusión" class="section level2">
<h2>5. Discusión</h2>
<p>En general, los resultados evidencian un efecto significativo de todas las variables incluidas en el modelo con respecto a los años de educación. Este efecto puede deberse al gran tamaño de la muestra utilizada, sumado a la relevancia de las variables independientes consideradas.</p>
<p>En cuanto a la situación de pobreza multidimensional, se observa que los años disminuyen cuando la condición es tal, lo que va en línea con lo planteado en la hipótesis y a la revisión de literatura. Se evidencia que las condiciones socioeconómicas juegan un papel importante en el desempeño educativo de las personas. Cuando la capacidad de satisfacer necesidades básicas es limitada, la educación tiende a sacrificarse en favor de una fuente de ingresos más inmediata. A su vez, quienes estudian en contextos de vulnerabilidad social suelen presentar mayores obstáculos a la hora de rendir, mantener la concentración o el interés, etc.</p>
<p>De forma similar, a medida que aumenta el nivel de escolaridad de la madre, aumenta la predicción de años de escolaridad, lo que puede deberse a una herencia educativa intergeneracional, en donde los niveles más altos de escolaridad de las madres generan un entorno propicio para el desenvolvimiento educativo de los/as hijos/as. De manera inversa, madres cuyos niveles de escolaridad son menores por lo general se insertan en contextos laborales más precarios, dificultando el garantizar una buena educación a sus hijos/as. En el caso de familias monoparentales con jefaturas femeninas (más frecuentes que jefaturas masculinas en este tipo de hogar) suele hacerse más complejo buscar apoyo para la crianza, lo que puede tener un impacto en el desarrollo educativo de los/as hijos/as. En el caso de la variable sexo, también tiene un efecto significativo, pese a no ser tan grande como el del resto de las variables. Se evidencia que el ser mujer implica poseer menos años de escolaridad, lo que también es coherente con la hipótesis inicial. Lo novedoso en este caso es que la mediana de años de escolaridad entre ambos grupos es similar, pero hay una mayor concentración de casos en los niveles inferiores de educación en comparación a la categoría de los hombres, lo que implica que hay más casos extremos de baja escolaridad en mujeres.</p>
<p>Finalmente, la variable edad resultó relevante para controlar la variación que pudiese existir en el modelo a causa de esta. Cabe mencionar que si bien se podría haber esperado una variación positiva de los años de escolaridad en función de la edad, dado que se necesita más edad para obtener más años de escolaridad, este no fue el caso. Esto puede deberse a que las generaciones más jóvenes tienen mayor acceso a la educación, como también mejores condiciones para mantenerse estudiando. Tales aseveraciones pueden ser fuente de estudios que profundicen en esta relación.</p>
<p>En cuanto a las limitaciones, es posible que al considerar la variación de los años de escolaridad en función del nivel educacional de la madre existan otras variables que estén mediando, tales como empleabilidad femenina, ruralidad, cuidado de otros familiares, etc., que no se estén considerando en el modelo, pero que expliquen la variación proveniente de dicha variable independiente.</p>
<div/>


<h2>6. Referencias</h2>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-catro_d_pobreza_2013" class="csl-entry">
Catro D., Liilian Inés, and Rufino Cano G. 2013. <span>“Pobreza y Vulnerabilidad. <span>Factores</span> de Riesgo En El Proceso Educativo.”</span> <em>Contextos Educativos. Revista de Educación</em>, no. 16 (June): 55–72. <a href="https://doi.org/10.18172/con.1290">https://doi.org/10.18172/con.1290</a>.
</div>
<div id="ref-chile_indicadores_2006" class="csl-entry">
Chile, Ministerio de Educación, and Departamento de Estudios y Desarrollo. 2006. <em>Indicadores de La Educación En <span>Chile</span></em>. Chile: Ministerio de Educación.
</div>
<div id="ref-cohen_statistical_1988" class="csl-entry">
Cohen, Jacob. 1988. <em>Statistical Power Analysis for the Behavioral Sciences</em>. 2nd ed. Hillsdale, N.J: L. Erlbaum Associates.
</div>
<div id="ref-escamilla_r_familias_2013" class="csl-entry">
Escamilla R, Daniela, Yohanna Parra, and Valeria Vásquez. 2013. <span>“Familias Monoparentales, Madres Solteras Jefas de Hogar.”</span> 2(15): 1–17. <a href="http://www.ubiobio.cl/miweb/webfile/media/357/Articulos/Art%C3%ADculo-%20Familias%20monoparentales.pdf">http://www.ubiobio.cl/miweb/webfile/media/357/Articulos/Art%C3%ADculo-%20Familias%20monoparentales.pdf</a>.
</div>
<div id="ref-instituto_nacional_de_estadistica_sintesis_2017" class="csl-entry">
Estadística, Instituto Nacional de. 2017. <span>“Síntesis de Resultados. <span>Censo</span> 2017.”</span> <a href="http://www.censo2017.cl/descargas/home/sintesis-de-resultados-censo2017.pdf">http://www.censo2017.cl/descargas/home/sintesis-de-resultados-censo2017.pdf</a>.
</div>
<div id="ref-garbanzo_vargas_factores_2014" class="csl-entry">
Garbanzo Vargas, Guiselle María. 2014. <span>“Factores Asociados Al Rendimiento Académico Tomando En Cuenta El Nivel Socioeconómico: <span>Estudio</span> de Regresión Múltiple En Estudiantes Universitarios.”</span> <em>Revista Electrónica Educare</em> 18 (1): 119–54. <a href="http://www.scielo.sa.cr/scielo.php?script=sci_abstract&amp;pid=S1409-42582014000100007&amp;lng=en&amp;nrm=iso&amp;tlng=es">http://www.scielo.sa.cr/scielo.php?script=sci_abstract&amp;pid=S1409-42582014000100007&amp;lng=en&amp;nrm=iso&amp;tlng=es</a>.
</div>
<div id="ref-herrera_macguire_rezago_2020" class="csl-entry">
Herrera MacGuire, María Paz. 2020. <span>“El <span>Rezago</span> <span>Escolar</span> En <span>Chile</span> Como Factor Determinante Del Fracaso Escolar : <span>Un</span> Problema Invisible.”</span> Thesis, Universidad del Desarrollo. Facultad de Gobierno. <a href="http://repositorio.udd.cl/handle/11447/3346">http://repositorio.udd.cl/handle/11447/3346</a>.
</div>
<div id="ref-montero_rojas_factores_2014" class="csl-entry">
Montero Rojas, Eiliana, Jeannette Villalobos Palma, and Astrid Valverde Bermúdez. 2014. <span>“Factores Institucionales, Pedagógicos, Psicosociales y Sociodemográficos Asociados Al Rendimiento Académico En La <span>Universidad</span> de <span>Costa</span> <span>Rica</span>: Un Análisis Multinivel.”</span> <em>RELIEVE - Revista Electrónica de Investigación y Evaluación Educativa</em> 13 (2). <a href="https://doi.org/10.7203/relieve.13.2.4208">https://doi.org/10.7203/relieve.13.2.4208</a>.
</div>
<div id="ref-oliva_88_2018" class="csl-entry">
Oliva, H. 2018. <span>“El 88% de Los Chilenos Termina La Educación Media. <span>Centro</span> de Políticas Públicas <span>UDD</span>.”</span> <em>La Tercera</em>. <a href="https://gobierno.udd.cl/cpp/noticias/2018/01/15/el-88-de-los-chilenos-termina-la-educacion-media-la-tercera/">https://gobierno.udd.cl/cpp/noticias/2018/01/15/el-88-de-los-chilenos-termina-la-educacion-media-la-tercera/</a>.
</div>
<div id="ref-rivero_reforma_2000" class="csl-entry">
Rivero, José. 2000. <span>“Reforma y Desigualdad Educativa En <span>América</span> <span>Latina</span>.”</span> <em>Revista Iberoamericana de Educación</em> 23 (May): 103–33. <a href="https://doi.org/10.35362/rie2301008">https://doi.org/10.35362/rie2301008</a>.
</div>
<div id="ref-shrestha_multigenerational_2020" class="csl-entry">
Shrestha, Vinish, and Rashesh Shrestha. 2020. <span>“Multigenerational <span>Effects</span> of <span>Education</span> <span>Reform</span>: <span>Mother</span>’s <span>Education</span> and <span>Children</span>’s <span>Human</span> <span>Capital</span> in <span>Nepal</span>.”</span> <em>The World Bank Economic Review</em> 34 (3): 698–729. <a href="https://doi.org/10.1093/wber/lhy036">https://doi.org/10.1093/wber/lhy036</a>.
</div>
<div id="ref-sierra_determinantes_2019" class="csl-entry">
Sierra, Dagoberto Santofimio, Ángel Gil de Miguel, Martha Viviana Botello Yusungaira, Lina Constanza Jiménez Marulanda, Laura Fernanda Monroy Tovar, and Gloria Alejandra Ramírez Gutiérrez. 2019. <span>“Determinantes Sociales e Inequidades En Salud de Niños y Niñas Con Dificultades En El Aprendizaje En Las Escuelas Públicas de La Ciudad de <span>Neiva</span> <span>Colombia</span>.”</span> <em>REIB: Revista Electrónica Iberoamericana</em> 13 (1): 149–69. <a href="https://dialnet.unirioja.es/servlet/articulo?codigo=7562731">https://dialnet.unirioja.es/servlet/articulo?codigo=7562731</a>.
</div>
<div id="ref-encuesta_de_caracterizacion_socioeconomica_observatorio_2017" class="csl-entry">
socioeconómica., Encuesta de caracterización. 2017. <span>“Observatorio Social. <span>Previsión</span> Social: Síntesis de Resultados.”</span> {PowerPoint}. Santiago de Chile: Ministerio de Desarrollo Social y Familia. <a href="http://observatorio.ministeriodesarrollosocial.gob.cl/storage/docs/casen/2017/Resultados_Prevision_Social_Casen_2017.pdf">http://observatorio.ministeriodesarrollosocial.gob.cl/storage/docs/casen/2017/Resultados_Prevision_Social_Casen_2017.pdf</a>.
</div>
<div id="ref-zeng_gender_2014" class="csl-entry">
Zeng, Junxia, Xiaopeng Pang, Linxiu Zhang, Alexis Medina, and Scott Rozelle. 2014. <span>“<span>GENDER</span> <span>INEQUALITY</span> <span>IN</span> <span>EDUCATION</span> <span>IN</span> <span>CHINA</span>: <span>A</span> <span>META</span>-<span>REGRESSION</span> <span>ANALYSIS</span>.”</span> <em>Contemporary Economic Policy</em> 32 (2): 474–91. <a href="https://doi.org/10.1111/coep.12006">https://doi.org/10.1111/coep.12006</a>.
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
